# permissions for end users to view backupjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: universal-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupjob-viewer-role
rules:
- apiGroups:
  - backup.javy.dev
  resources:
  - backupjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.javy.dev
  resources:
  - backupjobs/status
  verbs:
  - get
